### ISSUE TITLE
User Guide Missing

### ISSUE THREAD

**Issue by DarioS** [NKI-CCB/TRANSACT#1]
There are no instructions explaining input file formats, choice of parameters, code execution, or interpretation of results.

**Comment by saroudant** [comment]
Hello Dario,

Thanks for your interest in TRANSACT and for raising an interesting and fair point.

I will refactor documentation and make it available as soon as possible. In the meantime, you can refer to the reproduction code of our manuscript, for example (https://github.com/NKI-CCB/TRANSACT_manuscript), e.g. going from cell lines to PDXs : https://github.com/NKI-CCB/TRANSACT_manuscript/blob/main/figure_2/2C-I_PDX_predictions.ipynb
In case you run into any issue, please do not hesitate to contact me, I will be happy to help out.

Best regards,
Soufiane
