### ISSUE TITLE
transform function

### ISSUE THREAD

**Issue by zenglongjin** [NKI-CCB/TRANSACT#2]
When I type source_data=TRANSACT_clf.transform(source_data), an error is reported:
`AttributeError                            Traceback (most recent call last)
<ipython-input-72-02550951be9a> in <module>
----> 1 source_data=TRANSACT_clf.transform(source_data)
      2 
~\anaconda3\lib\site-packages\transact_dr-1.0.1-py3.8.egg\transact\TRANSACT.py in transform(self, X, center)
    403             Dataset projected on consensus features.
    404         """
--> 405         return self.interpolation_.transform(X, self.optimal_time, center=center)
    406 
    407 
AttributeError: 'TRANSACT' object has no attribute 'interpolation_'`
Thank you very much for your attention and consideration.

**Comment by saroudant** [comment]
Dear Longjin Zeng,

My apologies for the late answer.

Could you please provide me more information on the code you are using ? Specifically, I would need the variables you provide to the "fit" function in TRANSACT.
Also, are you using the GitHub version of TRANSACT, or the one installed with pip ? I (still) have not updated the pip version. I will do it ASAP, but in the meantime use the code from this repo (with "pip install .") should work.

Best regards,
Soufiane

**Comment by zenglongjin** [comment]
Thank you for your guidance and I solved the problem.
